insert into rules(name, description) values ('carte blanche', 'everything is allowed');
insert into rules(name, description) values ('human', 'something is allowed');
insert into rules(name, description) values ('subhuman', 'nothing is allowed');
insert into role(name) values ('manager');
insert into role(name) values ('developer');
insert into role(name) values ('boss');
insert into role_rules(role_id, rules_id) values (1, 2);
insert into role_rules(role_id, rules_id) values (3, 1);
insert into role_rules(role_id, rules_id) values (2, 3);
insert into users(fname, lname, email, role_id) values ('Sergey', 'Sidorov', 'sidor@mail.ru', 2);
insert into users(fname, lname, email, role_id) values ('Vasiliy', 'Petrov', 'petrov@mail.ru', 1);
insert into state(name) values ('free');
insert into state(name) values ('in progress');
insert into state(name) values ('completed');
insert into category(name) values ('high_priority');
insert into category(name) values ('middle_priority');
insert into category(name) values ('low_priority');
insert into item(name, description, users_id, category_id, state_id) values ('IO', 'record to file', 1, 1, 1);
insert into comments(description, item_id) values ('implement writing to the attached file', 1);
insert into attachs(file_name, url, item_id) values ('properties', 'c\users\document\project', 1);
